{% set version = "1.8.1" %}

package:
  name: spreg
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/spreg/spreg-{{ version }}.tar.gz
  sha256: 771ec6020f03db0cd9659e922e7df30242c0106cbefa65463715e64e23411de7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >=3.8
    - libpysal
    - numpy >=1.23
    - scipy >=0.11

test:
  imports:
    - spreg

about:
  home: https://github.com/pysal/spreg
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: PySAL Spatial Econometrics Package

extra:
  recipe-maintainers:
    - ocefpaf
    - pedrovma
    - jGaboardi
    - knaaptime
    - martinfleis
